DB_HOST=$1
DB_PORT=$2
DB_NAME=$3
DB_USER=$4
DB_PASSWORD=$5
BACKUP_FILE=$6
SCHEMA=$7

pg_restore -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -v $BACKUP_FILE

psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME << EOF
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $SCHEMA TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $SCHEMA TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA $SCHEMA TO $DB_USER;
EOF